
package com.storageservice.sport.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LocalApiSportModel", targetNamespace = "http://ws.sport.storageservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocalApiSportModel {


    /**
     * 
     * @return
     *     returns java.util.List<com.storageservice.sport.ws.Sport>
     */
    @WebMethod
    @WebResult(name = "sports", targetNamespace = "")
    @RequestWrapper(localName = "getSportsList", targetNamespace = "http://ws.sport.storageservice.com/", className = "com.storageservice.sport.ws.GetSportsList")
    @ResponseWrapper(localName = "getSportsListResponse", targetNamespace = "http://ws.sport.storageservice.com/", className = "com.storageservice.sport.ws.GetSportsListResponse")
    @Action(input = "http://ws.sport.storageservice.com/LocalApiSportModel/getSportsListRequest", output = "http://ws.sport.storageservice.com/LocalApiSportModel/getSportsListResponse")
    public List<Sport> getSportsList();

    /**
     * 
     * @return
     *     returns com.storageservice.sport.ws.Sport
     */
    @WebMethod
    @WebResult(name = "sport", targetNamespace = "")
    @RequestWrapper(localName = "getSport", targetNamespace = "http://ws.sport.storageservice.com/", className = "com.storageservice.sport.ws.GetSport")
    @ResponseWrapper(localName = "getSportResponse", targetNamespace = "http://ws.sport.storageservice.com/", className = "com.storageservice.sport.ws.GetSportResponse")
    @Action(input = "http://ws.sport.storageservice.com/LocalApiSportModel/getSportRequest", output = "http://ws.sport.storageservice.com/LocalApiSportModel/getSportResponse")
    public Sport getSport();

    /**
     * 
     * @param weather
     * @return
     *     returns java.util.List<com.storageservice.sport.ws.Sport>
     */
    @WebMethod
    @WebResult(name = "sportsbyWeather", targetNamespace = "")
    @RequestWrapper(localName = "getSportsByWeather", targetNamespace = "http://ws.sport.storageservice.com/", className = "com.storageservice.sport.ws.GetSportsByWeather")
    @ResponseWrapper(localName = "getSportsByWeatherResponse", targetNamespace = "http://ws.sport.storageservice.com/", className = "com.storageservice.sport.ws.GetSportsByWeatherResponse")
    @Action(input = "http://ws.sport.storageservice.com/LocalApiSportModel/getSportsByWeatherRequest", output = "http://ws.sport.storageservice.com/LocalApiSportModel/getSportsByWeatherResponse")
    public List<Sport> getSportsByWeather(
        @WebParam(name = "weather", targetNamespace = "")
        String weather);

    /**
     * 
     * @param accessToken
     * @param userId
     * @param sport
     * @param refreshToken
     * @return
     *     returns com.storageservice.sport.ws.Activity
     */
    @WebMethod
    @WebResult(name = "activity", targetNamespace = "")
    @RequestWrapper(localName = "getActivityBySport", targetNamespace = "http://ws.sport.storageservice.com/", className = "com.storageservice.sport.ws.GetActivityBySport")
    @ResponseWrapper(localName = "getActivityBySportResponse", targetNamespace = "http://ws.sport.storageservice.com/", className = "com.storageservice.sport.ws.GetActivityBySportResponse")
    @Action(input = "http://ws.sport.storageservice.com/LocalApiSportModel/getActivityBySportRequest", output = "http://ws.sport.storageservice.com/LocalApiSportModel/getActivityBySportResponse")
    public Activity getActivityBySport(
        @WebParam(name = "sport", targetNamespace = "")
        Sport sport,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param accessToken
     * @param userId
     * @param refreshToken
     * @return
     *     returns java.util.List<com.storageservice.sport.ws.Activity>
     */
    @WebMethod
    @WebResult(name = "favouriteActivity", targetNamespace = "")
    @RequestWrapper(localName = "getFavouriteActivity", targetNamespace = "http://ws.sport.storageservice.com/", className = "com.storageservice.sport.ws.GetFavouriteActivity")
    @ResponseWrapper(localName = "getFavouriteActivityResponse", targetNamespace = "http://ws.sport.storageservice.com/", className = "com.storageservice.sport.ws.GetFavouriteActivityResponse")
    @Action(input = "http://ws.sport.storageservice.com/LocalApiSportModel/getFavouriteActivityRequest", output = "http://ws.sport.storageservice.com/LocalApiSportModel/getFavouriteActivityResponse")
    public List<Activity> getFavouriteActivity(
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

}
