
package com.storageservice.sport.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "storageServiceSport", targetNamespace = "http://ws.sport.storageservice.com/", wsdlLocation = "https://storageservicesport.herokuapp.com/ws/storageServiceSport?wsdl")
public class StorageServiceSport
    extends Service
{

    private final static URL STORAGESERVICESPORT_WSDL_LOCATION;
    private final static WebServiceException STORAGESERVICESPORT_EXCEPTION;
    private final static QName STORAGESERVICESPORT_QNAME = new QName("http://ws.sport.storageservice.com/", "storageServiceSport");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://storageservicesport.herokuapp.com/ws/storageServiceSport?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STORAGESERVICESPORT_WSDL_LOCATION = url;
        STORAGESERVICESPORT_EXCEPTION = e;
    }

    public StorageServiceSport() {
        super(__getWsdlLocation(), STORAGESERVICESPORT_QNAME);
    }

    public StorageServiceSport(WebServiceFeature... features) {
        super(__getWsdlLocation(), STORAGESERVICESPORT_QNAME, features);
    }

    public StorageServiceSport(URL wsdlLocation) {
        super(wsdlLocation, STORAGESERVICESPORT_QNAME);
    }

    public StorageServiceSport(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STORAGESERVICESPORT_QNAME, features);
    }

    public StorageServiceSport(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StorageServiceSport(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocalApiSportModel
     */
    @WebEndpoint(name = "LocalApiSportImplPort")
    public LocalApiSportModel getLocalApiSportImplPort() {
        return super.getPort(new QName("http://ws.sport.storageservice.com/", "LocalApiSportImplPort"), LocalApiSportModel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalApiSportModel
     */
    @WebEndpoint(name = "LocalApiSportImplPort")
    public LocalApiSportModel getLocalApiSportImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.sport.storageservice.com/", "LocalApiSportImplPort"), LocalApiSportModel.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STORAGESERVICESPORT_EXCEPTION!= null) {
            throw STORAGESERVICESPORT_EXCEPTION;
        }
        return STORAGESERVICESPORT_WSDL_LOCATION;
    }

}
