
package com.storageservice.weather.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "storageServiceWeather", targetNamespace = "http://ws.weather.storageservice.com/", wsdlLocation = "https://storageserviceweather.herokuapp.com/ws/storageServiceWeather?wsdl")
public class StorageServiceWeather
    extends Service
{

    private final static URL STORAGESERVICEWEATHER_WSDL_LOCATION;
    private final static WebServiceException STORAGESERVICEWEATHER_EXCEPTION;
    private final static QName STORAGESERVICEWEATHER_QNAME = new QName("http://ws.weather.storageservice.com/", "storageServiceWeather");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://storageserviceweather.herokuapp.com/ws/storageServiceWeather?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STORAGESERVICEWEATHER_WSDL_LOCATION = url;
        STORAGESERVICEWEATHER_EXCEPTION = e;
    }

    public StorageServiceWeather() {
        super(__getWsdlLocation(), STORAGESERVICEWEATHER_QNAME);
    }

    public StorageServiceWeather(WebServiceFeature... features) {
        super(__getWsdlLocation(), STORAGESERVICEWEATHER_QNAME, features);
    }

    public StorageServiceWeather(URL wsdlLocation) {
        super(wsdlLocation, STORAGESERVICEWEATHER_QNAME);
    }

    public StorageServiceWeather(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STORAGESERVICEWEATHER_QNAME, features);
    }

    public StorageServiceWeather(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StorageServiceWeather(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherApi
     */
    @WebEndpoint(name = "WeatherApiImplPort")
    public WeatherApi getWeatherApiImplPort() {
        return super.getPort(new QName("http://ws.weather.storageservice.com/", "WeatherApiImplPort"), WeatherApi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherApi
     */
    @WebEndpoint(name = "WeatherApiImplPort")
    public WeatherApi getWeatherApiImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.weather.storageservice.com/", "WeatherApiImplPort"), WeatherApi.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STORAGESERVICEWEATHER_EXCEPTION!= null) {
            throw STORAGESERVICEWEATHER_EXCEPTION;
        }
        return STORAGESERVICEWEATHER_WSDL_LOCATION;
    }

}
